spring:
  freemarker:
    checkTemplateLocation: false
  #    suffix: .ftlh
  #    settings:
  #      recognize_standard_file_extensions: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://192.168.56.98:3306/luck?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      database: mysql
    open-in-view: false

image:
  path: D:/logs/images/